### ISSUE TITLE
Unsure what to select for confIntSize and nnLocfit in detectSingleOut

### ISSUE THREAD

**Issue by LouiseLogie** [Biometris/statgenHTP#1]
I am currently working though the statgen [example ](https://cran.r-project.org/web/packages/statgenHTP/vignettes/Overview_HTP.html) . I am now at the outlier phase with the detectSingleOut function. I am  wondering what I should fill in for the confIntSize and nnLocfit. It seems like the values change per dataset and I would like to understand on what that depends. 
Errors associated with my trials are:
> Error in lfproc(x, y, weights = weights, cens = cens, base = base, geth = geth,  :   newsplit: out of vertex space

and no outlier detected in the next step. 

Could you help me out?

**Comment by BartJanvanRossum** [comment]
There is more information about the outlier detection in the dedicated vignette and specifically in this section: https://biometris.github.io/statgenHTP/articles/vignettesSite/OutlierSingleObs_HTP.html#illustration-of-the-non-parametric-function

nnLocfit is a measure for the amount of smoothing applied. It takes a value between 0 and 1, with higher values giving a smoother curve    
a large confIntSize creates a wider confidence interval around the smoothed trend, leading to less outliers.

The settings of these parameters indeed very much depend on your data. In the linked vignette above there are three examples with 'correct' nnLocfit values of 0.1, 0.5 and 1.

I hope this helps in understanding what is going on.

Having said this, no matter what values you use, there shouldn't be in error. Did you get this error when using the exact example in the vignette you linked to or did you use your own settings and data? In the latter case, would it be possible to share your example?

**Comment by LouiseLogie** [comment]
Hi, thanks for the link! 
I am having issues using my own dataset, but the dummy dataset provided did work. 
How can I best share my example? 
Louise

**Comment by BartJanvanRossum** [comment]
Hi,
I think the easiest way is using surffilesender or something similar.
Using that it would be easy to share both your script and the data, so I can exactly replicate what you are doing
Bart-Jan

**Comment by BartJanvanRossum** [comment]
Closing this as it was mostly fixed after mail contact
