### ISSUE TITLE
Error when predicting fit.PSHDM

### ISSUE THREAD

**Issue by UQDannySmith** [Biometris/statgenHTP#2]
Hi, I am trying to run the predict function on a fitSplineHDM object I have created:

`fit.psHDM <- fitSplineHDM(inDat = spatiallycorrected,
    trait = 'dw_m2',
    pop = 'geno.decomp',
genotype = 'genotype',
plotId = 'plotId',
useTimeNumber = TRUE,
timeNumber = 'TT_cumulative',
difVar = list(geno = TRUE, plot = TRUE),
smoothPop = list(nseg = 7, bdeg = 3, pord = 2),
smoothGeno = list(nseg = 7, bdeg = 3, pord = 2),
smoothPlot = list(nseg = 7, bdeg = 3, pord = 2),
weights = "wt",
trace = TRUE)`

I have simply adapted the code from [ statgenHTP Tutorial 5](https://biometris.github.io/statgenHTP/articles/vignettesSite/HierarchicalDataModel_HTP.html) to my own data, which is probably causing the issue. When I run the code
`pred.psHDM <- predict(object = fit.psHDM,
                      newtimes = seq(min(fit.psHDM$time[["timeNumber"]]),
                                     max(fit.psHDM$time[["timeNumber"]]),
                                     length.out = 100),
                      pred = list(pop = FALSE, geno = FALSE, plot = TRUE),
                      se = list(pop = FALSE, geno = TRUE, plot = FALSE),
                      trace = TRUE)`

I get the error: 
`Error in FUN(X[[i]], ...) : 
  only defined on a data frame with all numeric-alike variables`
Could you suggest any possible reasons that I'm getting this error? The input data for the fitSplineHDM object is a

**Comment by BartJanvanRossum** [comment]
Your questions seems to be missing its last few words.     
Going by the error message it seems a column in the data that is supposed to be numerical, however without seeing your data it is hard to say what exactly is going on. Would it be possible for you to share (part of) your data, or at least the output of 
```r
str(fit.psHDM)
```

**Comment by UQDannySmith** [comment]
Hi Bart,
Thanks for the quick reply! I've included my dataset here and the code that I've used:
I've skipped a few steps where I remove outliers, but at least for me the code below still produces the same error. I thought maybe it was occuring because the maturity grouping (which I've used as the population level) was a factor, and not numeric, but changing it to numeric didn't fix the error.

```
library(statgenHTP)
library(tidyverse)

raw_df <- read.csv('biomass.csv') 
experiment = 'biomass'
raw_df <- raw_df %>% mutate(mat_group = as.numeric(as.factor(mat_group)))
head(raw_df)

# create timepoint object
TPobj <- createTimePoints(dat = raw_df,
                          experimentName = experiment,
                          genotype = "genotype",
                          timePoint = "date",
                          repId = 'rep',
                          plotId = "plot_id",
                          rowNum = "row", 
                          colNum = "range",
                          addCheck = FALSE)

# Fit models
modelFit <- fitModels(TP = TPobj,
                      trait = 'dw_m2',
                      geno.decomp = "mat_group",
                      useRepId = TRUE)

corrected <- getCorrected(modelFit) %>%
  separate(plotId, into = c('rowId','colId'),remove = FALSE)
head(corrected)
# Fit PSHDM
fit.psHDM <- fitSplineHDM(inDat = corrected,
                          trait = 'dw_m2_corr',
                          pop = 'geno.decomp',
                          genotype = 'genotype',
                          plotId = 'plotId',
                          useTimeNumber = FALSE,
                          difVar = list(geno = TRUE, plot = TRUE),
                          smoothPop = list(nseg = 7, bdeg = 3, pord = 2),
                          smoothGeno = list(nseg = 7, bdeg = 3, pord = 2),
                          smoothPlot = list(nseg = 7, bdeg = 3, pord = 2),
                          weights = "wt",
                          trace = TRUE)

# Predict PsHDM
pred.psHDM <- predict(object = fit.psHDM,
                      newtimes = seq(min(fit.psHDM$time[["timeNumber"]]),
                                     max(fit.psHDM$time[["timeNumber"]]),
                                     length.out = 100),
                      pred = list(pop = FALSE, geno = FALSE, plot = TRUE),
                      se = list(pop = FALSE, geno = TRUE, plot = FALSE),
                      trace = TRUE)

```
[biomass.csv](https://github.com/Biometris/statgenHTP/files/11163958/biomass.csv)

**Comment by BartJanvanRossum** [comment]
I think you are not using the latest version of statgenHTP. If I try to run your code for the last step, the predictions for the fitted HDM splines, I get this.

```r
Error in predict.psHDM(object = fit.psHDM, newtimes = seq(min(fit.psHDM$time[["timeNumber"]]), :
Predictions at plot level can only be made if predictions are also made at geno and pop level.
```

This makes sense, since the predictions at genotype and population level are used in the predictions at plot level. If I change your code to the code below everything works fine.
```r
pred.psHDM <- predict(object = fit.psHDM,
                      newtimes = seq(min(fit.psHDM$time[["timeNumber"]]),
                                     max(fit.psHDM$time[["timeNumber"]]),
                                     length.out = 100),
                      pred = list(pop = TRUE, geno = TRUE, plot = TRUE),
                      se = list(pop = TRUE, geno = TRUE, plot = FALSE),
                      trace = TRUE)
```

So to solve the problem you will first have to update statgenHTP to the latest CRAN version (1.0.6) and then modify you code in the way I suggested above.

**Comment by UQDannySmith** [comment]
Hi Bart, Thanks very much, this worked perfectly.
