### ISSUE TITLE
Combination of geno.decomp and what = "fixed"

### ISSUE THREAD

**Issue by kkjjag** [Biometris/statgenHTP#3]
Hello,

I would like to combine geno.decomp and what = "fixed" to generate BLUEs by treatment, rather than analysing each treatment separately. Would it be possible to include this in a future update?

Thank you!

**Comment by BartJanvanRossum** [comment]
Thanks for your suggestion. Unfortunately I won't be able to implement this. When fitting the models either SpATS or asreml is used. SpATS itself only accepts geno.decomp when genotype is fitted as random effect. For asreml it is possible to fit a model with genotype random and some for of geno.decomp. We tried this when developing the package, however the results using these kind of models were both unrealistic and inconsistent. Therefore we decided to not allow this in statgenHTP.

**Comment by kkjjag** [comment]
Thank you for your prompt and helpful response!
